### ISSUE TITLE
Suggestion: Option to show cooldowns

### ISSUE THREAD

**Issue by CypherGuy** [stshrewsburyDev/discord-better-help#3]
Right now, if there is a 30s cooldown on a command, it is shown as `30.0 second user`. Is there a way to disable showing this altogether, or if not, would it be possible to please?

**Comment by SkylaDev** [comment]
Thankyou for the suggestion.
I will get to work on adding an option to disable the cooldown field.
Will update this issue once complete (will work on it tomorrow when I have time)

**Comment by CypherGuy** [comment]
Thanks! If it's easier, you could also just change what it says, so it could say `30 seconds (User)` rather than `30.0 second user`. 

btw, your package has worked wonders for me, so thank you!

**Comment by SkylaDev** [comment]
Glad to hear it.
I have added an option to disable the cooldown field via `show_cooldown` (default is on True), as well as changing the way the cooldowns are displayed as your suggestion.
Instead of showing `30.0 second user` it will now preview as `30 seconds (User)` or `30.5 seconds (User)` if decimal place is required.
Full changelog here: https://discord-better-help.readthedocs.io/en/latest/changelogs/1.1.0.html

Thanks again for the suggestion submission, any more problems please dont heasitate to make another issue request!

**Comment by CypherGuy** [comment]
Thanks for doing this!

I've also noticed that when I've reran it, it's still showing `30 second user`. I have added a picture to show you. Do you have any idea why?
<img width="438" alt="Screenshot 2021-05-10 at 12 51 54" src="https://user-images.githubusercontent.com/74025064/117655887-90a36880-b18f-11eb-9208-9619fc4802e0.png">

**Comment by SkylaDev** [comment]
Only explanation I can think of is your still using the outdated version of the module, ensure you have updated to 1.1.0 and restarted your bot so it uses the new one and not any previous install that existed when you last ran it.

**Comment by CypherGuy** [comment]
How did I not think of that! Worked perfectly, thanks!
