### ISSUE TITLE
Add information header

### ISSUE THREAD

**Issue by CypherGuy** [stshrewsburyDev/discord-better-help#4]
In the picture I supplied, there' a `usage` and a `cooldown` title. I was wondering if there was an information / brief title I could add for the first box, or if not, a way to add that section, namely for the first codeblock.

Thanks!

P.s: Don't mind the cooldown feature from earlier, it works perfectly!
<img width="504" alt="Screenshot 2021-05-10 at 15 04 18" src="https://user-images.githubusercontent.com/74025064/117671724-0401a600-b1a1-11eb-8b74-6f1ce3480f15.png">

**Comment by SkylaDev** [comment]
Originally I designed the help menu to be similar to that of the default discord.py one hence why it does not show the brief description of commands.

I did design this however but was unable to get it to show above the long description due to Discord's embed system.
Is this what you mean?
![image](https://user-images.githubusercontent.com/39103023/117678461-50e87b00-b1a7-11eb-9e31-31b62483fa6d.png)

**Comment by CypherGuy** [comment]
No, what I had meant is that I think there should be a title called ‘info’ or something over the first box where it says “Tries to get a defined users..”, like with ‘Brief’ and “Gets user avatar”

Did that clarify it? If not, Im sure I will be fine otherwise.

**Comment by SkylaDev** [comment]
The only way that would be possible is to change that info box from the description to a field which would limit the characters down to 1024 instead of its current 2048 current character limit.
I will most likely add an option for you to set the description to a field (which would enable the title) but make it optional for people who prefer to use the current design that has a larger char limit.

**Comment by CypherGuy** [comment]
Oh, that makes more sense. I just thought it would look more pleasing aesthetically, but you don't need to do it.

Thanks though!

**Comment by SkylaDev** [comment]
![image](https://user-images.githubusercontent.com/39103023/117684243-b68b3600-b1ac-11eb-96fb-e1181ce38887.png)

**Comment by SkylaDev** [comment]
Ill release a quick 1.1.1 build of the module that will have this feature enabled, to enable it all you have to do is parse `show_info_title=True` into your Help class.

Example:
```python
from discord.ext import commands
from better_help import Help

bot = commands.Bot(command_prefix="!", help_command=Help(show_info_title=True))
```

**Comment by CypherGuy** [comment]
Perfect, thanks very much! I hope you don't mind me picking out stuff I would like, because what you’ve made is perfect for me.

**Comment by SkylaDev** [comment]
I dont mind your requests, If anything your requests are allowing me to modify the library in a way that makes it better for other users as well as yourself, originally I would have nether thought of this idea until you suggested it.

**Comment by CypherGuy** [comment]
Cool, I’ll see if I can suggest some other things later onwards!

**Comment by SkylaDev** [comment]
Coolio.
Just pushed the update out onto pypi. As mentioned before to enable the info title just parse `show_info_title=True` into the Help class.

Thanks again for the suggestion!
